export const projects = [
  {
    title: 'MERN Memories',
    description: "Social Media App Using React, Node.js, Express & MongoDB.",
      image: '/images/1.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://github.com/HristijanGjorgjioski/memories',
    visit: 'https://memories-gjorgjioski.netlify.app/',
    id: 0,
  },
  {
    title: 'Expense Tracker',
    description:"Expense Tracker app with React and Speechly!",
    image: 'https://i.ibb.co/3BscyCN/expense-tracker.png',
    tags: ['React', 'JavaScript', 'Speechly'],
    source: 'https://github.com/HristijanGjorgjioski/expense-tracker',
    visit: 'https://expense-tracker-gjorgjioski.netlify.app/',
    id: 1,
  },
  {
    title: 'WebRTC App',
    description: "React Video Chat Application using WebRTC.",
      image: '/images/3.jpg',
      tags: ['React', 'WebRTC', 'Socket.io'],
    source: 'https://github.com/HristijanGjorgjioski/VideoChatApp',
    visit: 'https://video-chat-gjorgjioski.netlify.app/',
    id: 2,
  },
  {
    title: 'Hbook',
    description: "Online code editor. Something like SandBox.",
    image: 'https://i.ibb.co/QfBJ5N5/hbook.png',
    tags: ['React', 'Typescript', 'MonacoEditor'],
    source: 'https://github.com/HristijanGjorgjioski/hbook',
    visit: 'https://hbook-gjorgjioski.netlify.app/',
    id: 3,
  },
  {
    title: 'Cryptoverse',
    description: "Crypto info and news application.",
    image: 'https://imgur.com/v4SdAod.png',
    tags: ['React', 'JavaScript', 'RapidAPI'],
    source: 'https://github.com/HristijanGjorgjioski/crypto-app',
    visit: 'https://cryptoverse-gjorgjioski.netlify.app/',
    id: 4,
  },
  {
    title: 'My own API',
    description: "Node.js api for user auth and post functionality",
    image: 'https://imgur.com/lT65YFm.png',
    tags: ['JavaScript', 'Node.js', 'MongoDB'],
    source: 'https://github.com/HristijanGjorgjioski/GorgAPI',
    visit: 'https://github.com/HristijanGjorgjioski/GorgAPI',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2020, text: 'Started my journey', },
  { year: 2021, text: 'Worked as a freelance developer', },
  { year: 2022, text: 'Started at coding bootcamp', },
];
